mongo:
  image: mongo
  volumes:
    - ./.data/runtime/db:/data/db
    - ./.data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:latest
  volumes:
    - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=http://XXXX
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 10030:3000

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat:latest
  volumes:
    - ./scripts:/home/hubot/scripts
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=
    - LISTEN_ON_ALL_PUBLIC=true
    - ROCKETCHAT_USER=xxxx
    - ROCKETCHAT_PASSWORD=xxxx
    - BOT_NAME=xxxx
    - GOOGLE_API_KEY=AIzaSyChP9FfAzorsVSXZ1HpYkhU4OAkgwBq2JM
    - GITLAB_URL="http://xxxx.xxxxx.cn/"
    - GITLAB_API_KEY="xxxxxx"
    - GITLAB_CHANNEL=gitlab_publish
    - GITLAB_BRANCHES="master,develop"
    - GITLAB_SHOW_COMMITS_LIST=0
    - GITLAB_SHOW_MERGE_DESCRIPTION=0
    - HUBOT_JENKINS_URL=xxxxxx
    - HUBOT_JENKINS_AUTH=xxxx:xxxx
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,basics,hubot-links,hubot-diagnostics,hubot-google,hubot-reddit,hubot-bofh,hubot-bookmark,hubot-shipit,hubot-maps,hubot-gitsy,hubot-baronbogo,hubot-qr,hubot-2048,hubot-jenkins
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 10031:8080